// بنك الأسئلة
const questionsBank = [
    // ================= LAB 1 =================
    { section: "lab1", q: "Qualitative analysis is used to detect:", opts: ["The amount of a substance", "The presence of a substance", "The density of a substance", "The molecular weight"], correct: 1 },
    { section: "lab1", q: "Quantitative analysis is used to determine:", opts: ["The presence of a substance", "The amount/concentration of a substance", "The boiling point", "The physical state"], correct: 1 },
    { section: "lab1", q: "A primary standard must NOT be:", opts: ["100% pure", "Stable at drying temperature", "Absorbing water or CO2", "Reacting stoichiometrically"], correct: 2 },
    { section: "lab1", q: "Why should a primary standard have a high equivalent weight?", opts: ["To increase solubility", "To minimize weighing errors", "To change indicator color faster", "To react slowly"], correct: 1 },
    { section: "lab1", q: "The point at which equal amounts of acid and base have reacted is called:", opts: ["End point", "Equivalence point", "Starting point", "Blank point"], correct: 1 },
    { section: "lab1", q: "Which experiment is used to correct background effects and impurities in the solvent?", opts: ["Blank experiment", "Standardization", "Titration", "Calibration"], correct: 0 },
    { section: "lab1", q: "A highly pure, stable substance used to determine unknown concentrations is:", opts: ["Analyte", "Primary standard", "Indicator", "Buffer"], correct: 1 },
    { section: "lab1", q: "The constituent of the sample to be studied is called:", opts: ["Titrant", "Analyte", "Blank", "Standard"], correct: 1 },
    { section: "lab1", q: "When reading colored solutions in glassware, you should read:", opts: ["The bottom of the meniscus", "The upper surface", "The middle", "The side"], correct: 1 },
    { section: "lab1", q: "When reading colorless liquids in glassware, you should read:", opts: ["The bottom of the meniscus", "The upper surface", "The middle", "The side"], correct: 0 },
    { section: "lab1", q: "When reading the meniscus correctly, the eye should be:", opts: ["Above the solution", "Below the solution", "At the same level as the solution", "At any angle"], correct: 2 },

    // ================= LAB 2 & 3 =================
    { section: "lab2_3", q: "What is the color of Methyl Orange in an acidic medium?", opts: ["Yellow", "Red", "Orange", "Colorless"], correct: 1 },
    { section: "lab2_3", q: "What is the color of Phenolphthalein in an alkaline medium?", opts: ["Pink/Violet", "Colorless", "Yellow", "Red"], correct: 0 },
    { section: "lab2_3", q: "The pH range of Methyl Orange is:", opts: ["8.2 - 10", "6.0 - 7.6", "3.2 - 4.4", "10.1 - 13.0"], correct: 2 },
    { section: "lab2_3", q: "The pH range of Phenolphthalein is:", opts: ["3.2 - 4.4", "8.2 - 10.0", "4.2 - 6.3", "6.0 - 7.6"], correct: 1 },
    { section: "lab2_3", q: "For a Strong Acid vs Strong Base titration, which indicator can be used?", opts: ["Phenolphthalein only", "Methyl Orange only", "Any indicator", "None"], correct: 2 },
    { section: "lab2_3", q: "For a Weak Acid vs Strong Base titration, which indicator MUST be used?", opts: ["Phenolphthalein", "Methyl Orange", "Methyl Red", "Bromothymol blue"], correct: 0 },
    { section: "lab2_3", q: "Why can't Methyl Orange be used for Weak Acid vs Strong Base?", opts: ["It changes color in alkaline pH", "The inflection point is short and alkaline (6-11)", "It destroys the buffer", "It reacts with the strong base"], correct: 1 },
    { section: "lab2_3", q: "Solutions that resist changes in pH are called:", opts: ["Standard solutions", "Blank solutions", "Buffer solutions", "Indicators"], correct: 2 },
    { section: "lab2_3", q: "An acidic buffer consists of:", opts: ["Weak base + its salt", "Strong acid + strong base", "Weak acid + its salt", "Strong base + its salt"], correct: 2 },
    { section: "lab2_3", q: "Buffer capacity depends on:", opts: ["Buffer ratio only", "Buffer type only", "Concentration only", "Buffer ratio, type, and concentration"], correct: 3 },
    { section: "lab2_3", q: "At half-neutralization point in a buffer system:", opts: ["pH = 7", "pH = pKa", "pOH = pKa", "Salt concentration = 0"], correct: 1 },
    { section: "lab2_3", q: "Increasing the salt concentration in an acidic buffer will:", opts: ["Decrease pH", "Increase pH", "Destroy the buffer", "Produce precipitate"], correct: 1 },
    { section: "lab2_3", q: "Increasing the weak acid concentration in an acidic buffer will:", opts: ["Increase pH", "Decrease pH", "Make pH = 7", "Remove buffer action"], correct: 1 },
    { section: "lab2_3", q: "The end point of a Weak Acid vs Strong Base titration is:", opts: ["Acidic", "Neutral", "Alkaline", "Colorless"], correct: 2 },
    { section: "lab2_3", q: "The end point of a Strong Acid vs Strong Base titration is approximately:", opts: ["pH 1", "pH 4", "pH 7", "pH 10"], correct: 2 },

    // ================= LAB 4 & 5 =================
    { section: "lab4_5", q: "In a Carbonate & Bicarbonate mixture, Phenolphthalein reacts with:", opts: ["All Carbonate", "Half the Carbonate only", "All Bicarbonate", "Both Carbonate and Bicarbonate"], correct: 1 },
    { section: "lab4_5", q: "In a Carbonate & Bicarbonate mixture, Methyl Orange reacts with:", opts: ["Half Carbonate", "All Bicarbonate only", "All Carbonate + Bicarbonate", "None of them"], correct: 2 },
    { section: "lab4_5", q: "Borax hydrolyzes in water to produce:", opts: ["Boric acid + HCl", "Boric acid + NaOH", "Sodium carbonate", "Formaldehyde"], correct: 1 },
    { section: "lab4_5", q: "In Borax mixture, NaOH is titrated first using:", opts: ["Phenolphthalein", "Methyl Orange", "Murexide", "Erio-T"], correct: 1 },
    { section: "lab4_5", q: "Why can't Boric acid be titrated directly with NaOH?", opts: ["It is a strong acid", "It evaporates", "It is too weak", "It forms a precipitate"], correct: 2 },
    { section: "lab4_5", q: "What is added to Boric acid to make it titratable?", opts: ["Ether", "Formaldehyde", "Nitrobenzene", "Glycerol"], correct: 3 },
    { section: "lab4_5", q: "What is the function of Glycerol in Boric acid titration?", opts: ["Acts as an indicator", "Forms a stronger complex releasing H+", "Neutralizes NaOH", "Extracts the acid"], correct: 1 },
    { section: "lab4_5", q: "Bicarbonate is ________ to Phenolphthalein indicator.", opts: ["Alkaline", "Neutral", "Acidic", "Precipitant"], correct: 2 },
    { section: "lab4_5", q: "Carbonate is ________ to Phenolphthalein indicator.", opts: ["Alkaline", "Neutral", "Acidic", "Precipitant"], correct: 0 },
    { section: "lab4_5", q: "The quantity of glycerol added to Boric acid must be:", opts: ["5-10% of total volume", "30-50% of total volume", "100% of total volume", "Just 2 drops"], correct: 1 },

    // ================= LAB 6 =================
    { section: "lab6", q: "Formol titration is used to determine:", opts: ["Sodium Salicylate", "Carbonates", "Ammonium salts", "Zinc ions"], correct: 2 },
    { section: "lab6", q: "In Formol titration, formaldehyde is added to produce:", opts: ["Hexamine + Acid", "Ether + Base", "Borax", "Silver Chloride"], correct: 0 },
    { section: "lab6", q: "Which indicator is used in Formol titration?", opts: ["Methyl Orange", "Phenolphthalein", "Bromophenol blue", "Murexide"], correct: 1 },
    { section: "lab6", q: "Biphasic titration is used to determine:", opts: ["Ammonium chloride", "Sodium Salicylate", "Borax", "Calcium"], correct: 1 },
    { section: "lab6", q: "Why is Ether added in the titration of Sodium Salicylate?", opts: ["To act as an indicator", "To dissolve the sodium", "To extract the liberated salicylic acid", "To increase the pH"], correct: 2 },
    { section: "lab6", q: "What is the solubility ratio of salicylic acid in ether compared to water?", opts: ["1:1", "10:1", "100:1", "250:1"], correct: 3 },
    { section: "lab6", q: "Which indicator is used in Biphasic titration (Sodium Salicylate)?", opts: ["Bromophenol blue", "Phenolphthalein", "Methyl Orange", "Erio-T"], correct: 0 },
    { section: "lab6", q: "What is the end point color in Biphasic titration?", opts: ["Pink", "Brick red", "Full Green", "Colorless"], correct: 2 },
    { section: "lab6", q: "In Biphasic titration, a bluish-green color indicates:", opts: ["End point", "Under titration", "Over titration", "Error"], correct: 1 },
    { section: "lab6", q: "In Biphasic titration, a yellowish-green color indicates:", opts: ["End point", "Under titration", "Over titration", "Error"], correct: 2 },

    // ================= LAB 7 =================
    { section: "lab7", q: "Mohr's method is performed in which pH medium?", opts: ["Highly acidic", "Neutral or slightly alkaline (6.5 - 9)", "Strongly alkaline (> 9)", "Very acidic (< 2)"], correct: 1 },
    { section: "lab7", q: "What is the indicator used in Mohr's method?", opts: ["Ferric Alum", "Potassium Chromate", "Erio-T", "Diphenylamine"], correct: 1 },
    { section: "lab7", q: "What is the end point in Mohr's method?", opts: ["Blood red solution", "White precipitate", "Brick red precipitate", "Violet color"], correct: 2 },
    { section: "lab7", q: "What happens if Mohr's method is performed in an Acidic medium (< 6.5)?", opts: ["AgCl dissolves", "Black Ag2O forms", "Soluble silver dichromate forms", "Blood red complex forms"], correct: 2 },
    { section: "lab7", q: "What happens if Mohr's method is performed in a strongly Alkaline medium (> 9)?", opts: ["Soluble silver dichromate forms", "Black silver oxide (Ag2O) forms", "Ammonia dissolves AgCl", "Nothing happens"], correct: 1 },
    { section: "lab7", q: "What is the effect of Ammonia if present in Mohr's method?", opts: ["Forms a black ppt", "Dissolves the AgCl precipitate", "Changes indicator color", "Increases acidity"], correct: 1 },
    { section: "lab7", q: "Volhard's method is performed in which pH medium?", opts: ["Neutral", "Slightly alkaline", "Highly Acidic (HNO3)", "Strongly alkaline"], correct: 2 },
    { section: "lab7", q: "Why is Volhard's method done in a Highly Acidic medium?", opts: ["To dissolve AgCl", "To prevent Ag2O formation and favor the indicator complex", "To form a black ppt", "To extract the acid"], correct: 1 },
    { section: "lab7", q: "What is the indicator used in Volhard's method?", opts: ["Ferric Alum", "Potassium Chromate", "Phenolphthalein", "Xylenol Orange"], correct: 0 },
    { section: "lab7", q: "What is the end point in Volhard's method?", opts: ["Brick red ppt", "Full green color", "Colorless", "Blood red solution"], correct: 3 },
    { section: "lab7", q: "In Volhard's method for Chloride, why MUST AgCl be removed before back titration?", opts: ["Because AgCl is volatile", "Because AgSCN is less soluble than AgCl", "Because it reacts with the indicator", "To change the pH"], correct: 1 },
    { section: "lab7", q: "Which of the following is NOT a method to remove AgCl in Volhard's method?", opts: ["Filtration", "Adding Nitrobenzene", "Boiling for 3 minutes", "Adding Ether"], correct: 3 },
    { section: "lab7", q: "Mohr's method is considered:", opts: ["Back titration", "Direct titration", "Complexometric titration", "Redox titration"], correct: 1 },
    { section: "lab7", q: "Volhard's method is considered:", opts: ["Direct titration", "Neutralization titration", "Back titration", "Complexometric titration"], correct: 2 },
    { section: "lab7", q: "Why is the concentration of potassium chromate critical in Mohr's method?", opts: ["To avoid early formation of Ag2CrO4", "To dissolve AgCl", "To increase acidity", "To precipitate AgOH"], correct: 0 },
    { section: "lab7", q: "Why can HCl NOT be used in Volhard's method?", opts: ["Because it oxidizes SCN-", "Because AgCl precipitates", "Because it forms Ag2O", "Because ferric alum dissolves"], correct: 1 },
    { section: "lab7", q: "Why can H2SO4 NOT be used in Volhard's method?", opts: ["Because Ag2SO4 precipitates", "Because it is weak acid", "Because it forms AgCl", "Because it destroys indicator"], correct: 0 },
    { section: "lab7", q: "Why can iodide not be determined accurately by Mohr's method?", opts: ["Because AgI adsorbs chromate strongly", "Because iodide is acidic", "Because AgI is soluble", "Because K2CrO4 reacts with iodide"], correct: 0 },

    // ================= LAB 8 & 9 =================
    { section: "lab8_9", q: "EDTA forms highly stable chelates in which medium?", opts: ["Acidic", "Neutral", "Alkaline", "Biphasic"], correct: 2 },
    { section: "lab8_9", q: "Why does EDTA stability increase in alkaline medium?", opts: ["It neutralizes the liberated H+ ions", "It precipitates the metals", "It changes the indicator color directly", "It dissolves the salts"], correct: 0 },
    { section: "lab8_9", q: "What is the mechanism of Metallochrome indicators?", opts: ["Redox reaction", "EDTA displaces the indicator (Complexed to Free color)", "Acid-base neutralization", "Precipitation"], correct: 1 },
    { section: "lab8_9", q: "What is the color change of Erio-T indicator at the end point?", opts: ["Pink to Purple", "Red to Lemon Yellow", "Wine red to Blue", "Violet to Colorless"], correct: 2 },
    { section: "lab8_9", q: "Erio-T indicator is used at which pH?", opts: ["pH 2", "pH 5", "pH 8-10", "pH 12"], correct: 2 },
    { section: "lab8_9", q: "What is the color change of Murexide indicator at the end point?", opts: ["Wine red to Blue", "Pink to Purple", "Red to Lemon Yellow", "Blood red to Colorless"], correct: 1 },
    { section: "lab8_9", q: "Murexide indicator is used at which pH?", opts: ["pH 5", "pH 8-10", "pH 12", "Highly acidic"], correct: 2 },
    { section: "lab8_9", q: "In a Ca & Mg mixture, Total (Ca+Mg) is titrated at:", opts: ["pH 12 using Murexide", "pH 10 using Erio-T", "pH 5 using Xylenol Orange", "pH 8 using Potassium Chromate"], correct: 1 },
    { section: "lab8_9", q: "In a Ca & Mg mixture, Calcium ONLY is titrated at:", opts: ["pH 10 using Erio-T", "pH 12 using Murexide", "pH 5 using Xylenol Orange", "pH 7 using Ferric Alum"], correct: 1 },
    { section: "lab8_9", q: "Why is Calcium titrated at pH 12 to determine it alone in the mixture?", opts: ["Because Ca dissolves completely", "Because Mg precipitates as Mg(OH)2 and doesn't interfere", "Because EDTA works only at pH 12", "Because Murexide is blue at pH 12"], correct: 1 },
    { section: "lab8_9", q: "Why is Murexide used instead of Erio-T to determine Calcium alone?", opts: ["Because Erio-T precipitates at pH 12", "Because Erio-T forms a very weak complex with Calcium", "Because Murexide reacts with Mg", "Because Erio-T is colorless"], correct: 1 },
    { section: "lab8_9", q: "Xylenol Orange indicator changes color from Red to Lemon Yellow in:", opts: ["Alkaline medium", "Neutral medium", "Acidic medium", "Biphasic medium"], correct: 2 },
    { section: "lab8_9", q: "EDTA is considered a:", opts: ["Monodentate ligand", "Bidentate ligand", "Multidentate ligand", "Indicator"], correct: 2 },
    { section: "lab8_9", q: "EDTA is considered NON-selective because:", opts: ["It reacts with acids only", "It forms complexes with many metal ions", "It changes color rapidly", "It works only at pH 12"], correct: 1 },
    { section: "lab8_9", q: "The stability of metal-EDTA complex depends mainly on:", opts: ["Temperature only", "Indicator only", "Metal type and pH", "Color of solution"], correct: 2 },
    { section: "lab8_9", q: "Trivalent metal ions form ______ complexes with EDTA than divalent ions.", opts: ["Less stable", "More stable", "No", "Colored"], correct: 1 },
    { section: "lab8_9", q: "Why does EDTA displace the indicator from the metal-indicator complex?", opts: ["Because EDTA is acidic", "Because EDTA forms a more stable complex with the metal ion", "Because EDTA changes the pH", "Because the indicator precipitates"], correct: 1 },
    { section: "lab8_9", q: "In EDTA titration, the indicator changes from:", opts: ["Free color to complexed color", "Complexed color to free color", "Acidic to alkaline", "Blue to red only"], correct: 1 },
    { section: "lab8_9", q: "Why is Xylenol Orange used at pH 5?", opts: ["Because Zn2+ forms stable EDTA complex in slightly acidic medium", "Because EDTA works only in acidic medium", "Because Erio-T precipitates", "Because pH 5 dissolves EDTA"], correct: 0 },


    // ================= LAB 10 =================
    { section: "lab10", q: "Diphenylamine changes color according to the ratio between:", opts: ["Acid and base", "Ferricyanide and Ferrocyanide", "EDTA and metal", "Ag+ and Cl-"], correct: 1 },
    { section: "lab10", q: "At the equivalence point in Zinc titration, which form predominates?", opts: ["Ferricyanide", "Ferrocyanide", "Diphenylamine oxidized form", "Zn2+"], correct: 1 },
    { section: "lab10", q: "What is the indicator used in the determination of Zinc by Ferrocyanide?", opts: ["Phenolphthalein", "Diphenylamine", "Murexide", "Erio-T"], correct: 1 },
    { section: "lab10", q: "Diphenylamine is considered a:", opts: ["Acid-Base indicator", "Metallochrome indicator", "Redox indicator", "Precipitation indicator"], correct: 2 },
    { section: "lab10", q: "Before the end point in Zinc titration, which form predominates?", opts: ["Ferrocyanide (Reduced)", "Ferricyanide (Oxidized)", "Zinc hydroxide", "Diphenylamine free form"], correct: 1 },
    { section: "lab10", q: "What is the color of the solution BEFORE the end point (Zinc titration)?", opts: ["Colorless", "Lemon Yellow", "Brick Red", "Violet"], correct: 3 },
    { section: "lab10", q: "What is the color of the solution AT the end point (Zinc titration)?", opts: ["Violet", "Colorless", "Blood Red", "Blue"], correct: 1 },
    { section: "lab10", q: "What causes the sudden change to colorless at the equivalence point?", opts: ["Precipitation of Zinc", "First drop of excess Ferrocyanide reducing the indicator", "Oxidation by Ferricyanide", "Evaporation of the solvent"], correct: 1 },
    { section: "lab10", q: "Why is a small amount of Ferricyanide added in the beginning?", opts: ["To act as a buffer", "To oxidize the indicator to its violet color before the end point", "To dissolve the Zinc", "To decrease the pH"], correct: 1 },
    { section: "lab10", q: "In this redox system, Ferrocyanide represents the:", opts: ["Oxidized form", "Reduced form", "Acidic form", "Basic form"], correct: 1 }
];
